spring:
  datasource:
    url: jdbc:postgresql://localhost:5655/uni-cms?stringtype=unspecified
    username: postgres
    password: 22305
    hibernate:
      ddl-auto: none


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
